### ISSUE TITLE
Adding CSS for different Components in a wrong way, apply it to all components ⚡️⚡️⚡️

### ISSUE THREAD

**Issue by gk-git** [OussamaGhamian/WeRiseByLiftingOthers#10]
Lets take the following example of a React component in your project:

```js

export default class contactus extends Component{
    render() {
        return (

            <div className="App" >
                <div className="Container1">
                    <div className="name">
                        <h2>Contact Us</h2>
                    </div>
                    <div className="three">
                        <div className="fak"><i className="material-icons">add_location</i>
                            <p className="mb-4">
                                <span className="add_location"></span>
                                <span>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae omnis, beatae qui quis ut ipsam,
                        ratione animi exercitationem perspiciatis hic iusto harum maiores iure labore atque sapiente laboriosam ad
            libero. </span>
                            </p>
                        </div>

                        <div className="num"><i className="material-icons">call</i>
                            <p className="mb-4">
                                <span className="call"></span>
                                <a href="#">+phone: +1 232 3235 324</a>
                            </p>
                        </div>
                        <div className="email"><i className="material-icons">contact_mail</i>
                            <p className="mb-0">
                                <span className="contact_mail"></span>
                                <a href="mailto:youremail@domain.com">youremail@domain.com</a>
                            </p>
                        </div>
                    </div>


                    <div className="form">
                        <form className="ff" />
                        <h4>Contact Form</h4>
                        <div className="fn">


                            <label for="fname">First Name</label>
                            <input type="text" id="fname" name="firstname" placeholder="Your name.." />

                            <label for="lname">Last Name</label>
                            <input type="text" id="lname" name="lastname" placeholder="Your last name.." />


                            <label for="subject"> Subject </label>
                            <input type="text" id="subject" name="subject" placeholder="your subject.." />

                            <label for="email">Email</label>
                            <input type="text" id="email" name="email" placeholder="your email.." />

                            <label for="msg">Message</label>
                            <textarea id="msg" name="msg" placeholder="Write something.." style={{ height: '200px' }}></textarea>

                            <input type="submit" value="send message" />

                        </div>
                    </div>

                </div>

            </div>

        );
    }
}

```

And its related CSS file 

```css
@import url('https://fonts.googleapis.com/css?family=Montserrat:400,500,600&display=swap');
@import url('https://fonts.googleapis.com/css?family=Montserrat:400,500,600&display=swap');


.Container1 {
    width: 80%;
    font-style: italic;
    margin: 20px auto;
    padding: 10px;
}

h2 {
    text-align: center;
    color: blue;
}

.three {
    display: flex;
    justify-content: space-between;

}

.num,
.email,
.fak {
    max-width: 33%
}

.num {
    margin-right: 100px;
}


input[type=text],
select,
textarea {
    width: 100%;
    padding: 12px;
    border: 1px solid #ccc;
    border-radius: 30px;
    box-sizing: border-box;
    margin-top: 6px;
    margin-bottom: 16px;
    resize: vertical;
}

input[type=submit] {
    background-color: blue;
    color: white;
    padding: 12px 20px;
    border: none;
    border-radius: 30px;
    cursor: pointer;
}

input[type=submit]:hover {
    background-color: rgb(36, 179, 7);
}


.material-icons {
    margin-left: 40%;
    color: blue;
}

.form {
    background-color: white;
    padding: 3%;
    background-color: transparent;
}

@media (max-width: 500px) {
    .Container1 {
        width: 100%;

        margin: 20px auto;
        padding: 10px;

    }

    .three {
        margin: 20px auto;
        padding: 10px;
        width: 100%;
        display: flex;
        flex-direction: column;

        align-items: center;

    }

    .num,
    .email,
    .fak {
        max-width: 80%;
    }

    .num {
        margin-right: 0;
    }
}
```

## In the CSS code you aren't prefixing your CSS which is a big red flag that will result in CSS conflict.

# The solution
## In React
1. Replace the className `App` with the component name ( the name should be all lowercase and each word is seperated by a hyphen `-`.   For example Component name  `ContactUs` => Parent CSS classname should be `contact-us`.

## In CSS 
1. for every rule in your component CSS file, prefix the rule with the component parent div className.
For example for 
```css
.Container1 {
    width: 80%;
    font-style: italic;
    margin: 20px auto;
    padding: 10px;
}

h2 {
    text-align: center;
    color: blue;
}

.three {
    display: flex;
    justify-content: space-between;

}
```
They should be:
```css
.contact-us .Container1 {
    width: 80%;
    font-style: italic;
    margin: 20px auto;
    padding: 10px;
}

.contact-us h2 {
    text-align: center;
    color: blue;
}

.contact-us .three {
    display: flex;
    justify-content: space-between;

}

```

That way you will make sure that when adding a CSS rule it will not break another css rule in a different component
